fix: only apply the AppExport transformation to the actual `root.tsx` file
forge42dev/Remix-Dev-Tools pull request #114
Opened 2024-03-13 02:41 UTC by br0p0p

# Description

I encountered an issue where any files matching the pattern `*root.tsx` were being treated as the `app/root.tsx` and receiving the same transformation.

This resolves this issue by only matching on the exact path of the app `root.tsx` file based on the Vite root directory and the Remix `appDirectory`.

**Before**

Root transforms are applied to any file matching `**/*root.tsx`:

- `app/root.tsx` ✅ 
- `app/components/card-root.tsx` ✅ 
- `app/routes/_auth.root.tsx` ✅ 

**After**

Root transforms are only applied to the _actual_ `root.tsx` file as determined by Remix

- `app/root.tsx` ✅ 
- `app/components/card-root.tsx` 🚫
- `app/routes/_auth.root.tsx` 🚫

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] This change requires a documentation update

# How Has This Been Tested?

I have an app with files such as:

- `app/root.tsx`
- `app/components/card-root.tsx`
- `app/components/dialog-root.tsx`

Using this plugin before this change caused the following error: `AppExport is not defined`

With these changes, the app runs and the dev tools are correctly included in the running app.

- [ ] Unit tests

# Checklist:

- [x] My code follows the guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-13 02:50 UTC, br0p0p commented
I'm happy to add docs here for the new `appDirectory` config but there wasn't an obvious place for it. Let me know how to proceed here.

Ideally, this `appDirectory` value would be reused from the existing `remix` plugin but I'm not sure how feasible that is.

2024-03-13 10:39 UTC, AlemTuzlak commented on src/vite/plugin.tsx
> +import path from "node:path";
this will probably need to be a conditional import

2024-03-13 10:40 UTC, AlemTuzlak commented on src/vite/plugin.tsx
> +  let rootDir = process.cwd();
also I'm not sure if this is required or not, this would probably break the deployments as well as not all env have process defined.

2024-03-13 10:42 UTC, AlemTuzlak requested changes
@br0p0p this is an interesting problem. Thank you for this, so I've left a few comments. The biggest issue with this approach is that I think when bundled this would cause issues in production environments that do not have a global process and node bindings, as v4 now allows deployments to anywhere thanks to using only node stuff conditionally this might be an issue.

If you don't want to work on this I can take care of it

2024-03-13 14:32 UTC, br0p0p commented
@AlemTuzlak I can make those updates. 

Forgive me if I'm not understanding but doesn't Vite rely on Node internals? So if someone's using Vite isn't Node a given? At least, for the build runtime. The build output won't have any reliance on Node internals AFAIK other than any Node usages within the app itself.

2024-03-14 10:53 UTC, AlemTuzlak commented
@br0p0p so I've tested this and this does not work on Windows. I've added a simple `.endsWith("/root.tsx")` for now I'd have to test this out more a bit to figure out what is going on but you can try with 4.0.8 and see if that solves the issue

2024-09-17 09:52 UTC, closed without merging